Feature/Us-70
alkemyTech/OT212-Server pull request #69
Opened 2022-06-02 18:32 UTC by fedegrios

Send a email when contact is added.

![mail_business](https://user-images.githubusercontent.com/8538976/171701324-6ffe4aa0-988c-4026-878d-cfadb0a6147d.JPG)
![mail_swagger](https://user-images.githubusercontent.com/8538976/171701327-73f31364-bf5c-4d2f-9622-c7dbacc236bd.JPG)
![mail_recibido](https://user-images.githubusercontent.com/8538976/171701328-000a18e8-bb0b-4257-a83d-cfd5b4644679.JPG)

2022-06-02 20:34 UTC, emmanuelranone approved these changes

2022-06-02 20:34 UTC, emmanuelranone requested changes
Faltaría que utilices la ´plantilla html

2022-06-02 23:04 UTC, fedegrios commented
Use email html template.

![image](https://user-images.githubusercontent.com/8538976/171752113-b4ae551e-cd26-43f5-b353-3c42397781ce.png)

2022-06-03 11:25 UTC, emmanuelranone approved these changes

2022-06-03 11:25 UTC, merged